### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by bardmc** [icek/ash.ts#1]
This is great and I'd love to use it in the project I'm working on, but we're heavily reliant on npm, would you be publish this as an npm package?

Thanks

**Comment by icek** [comment]
I'm planning to do this when `ash/io` package will be done (it's almost ready). Also there are a few things that I have to rethink before publishing to npm, eg. `@keep()` in nodes.
For now you can use this package with npm by installing directly from github:
`npm i -S icek/ash.ts`

**Comment by icek** [comment]
It's now poblished as [@ash.ts/ash](https://www.npmjs.com/package/@ash.ts/ash)
