### ISSUE TITLE
Change module name to "ash.ts" instead of "ash" in dist/ash.d.ts

### ISSUE THREAD

**Issue by andresa88** [icek/ash.ts#3]
This way you can import the ash modules in a typescript based project like so:

```
import { Engine, Entity } from "ash.ts";

let engine:Engine = new Engine();
```

when ash.ts is installed under the project's local node_modules/ directory. This way no path aliases need to be added to the project's tsconfig.json or webpack.config.js configuration files, it will just work.

**Comment by icek** [comment]
Fixed in [c0b2c9a42510a2e92839495a893955b9a4ab9324](https://github.com/icek/ash.ts/commit/c0b2c9a42510a2e92839495a893955b9a4ab9324)
