### ISSUE TITLE
TypeError: types is not iterable

### ISSUE THREAD

**Issue by Maniae** [icek/ash.ts#4]
Hi, thank you for porting this library to Typescript !

I've encountered an issue while trying to add a ListIteratingSystem to a new Engine :

> TypeError: types is not iterable
>     at ComponentMatchingFamily.init (...\node_modules\ash.ts\dist\ash.ts.js:625:44)
>     at new ComponentMatchingFamily (...\node_modules\ash.ts\dist\ash.ts.js:611:12)
>     at Engine.getNodeList (...\node_modules\ash.ts\dist\ash.ts.js:972:22)
>     at ControlSystem.addToEngine (...\node_modules\ash.ts\dist\ash.ts.js:2073:30)
>     at Engine.addSystem (...\node_modules\ash.ts\dist\ash.ts.js:1009:14

This seems to happens because of [this change](https://github.com/icek/ash.ts/commit/68b164e5c2a7a3e941eeb1cc47cf50fc0878ed15#diff-bfc4f02ebd0917cc814bb166d2176cfbR53).

Where `types` is undefined.

The issue can be "fixed" by overriding the `addToEngine() `function in the System.
Not sure if the issue is the fact that we try to iterate over an undefined variable of the fact that the variable should be defined though.

EDIT : I tried to run the function on client side, and it worked. Looks like the issue is related to node.

**Comment by icek** [comment]
Hi,

thanks for reporting this. Could you provide a sample of the code in which this problem occurs? 

Soon, in a separate repo, I will make available asteroids game that works without any problems with the master code version.

Here is an example usage of `ListIteratingSystem` from that game:
```ts
import { ListIteratingSystem } from 'ash.ts';
import { Bullet } from '../components';
import { EntityCreator } from '../EntityCreator';
import { BulletAgeNode } from '../nodes';

export class BulletAgeSystem extends ListIteratingSystem<BulletAgeNode> {
  private creator:EntityCreator;

  constructor(creator:EntityCreator) {
    super(BulletAgeNode);
    this.creator = creator;
  }

  public updateNode(node:BulletAgeNode, time:number):void {
    const bullet:Bullet = node.bullet;
    bullet.lifeRemaining -= time;
    if(bullet.lifeRemaining <= 0) {
      this.creator.destroyEntity(node.entity!);
    }
  }
}
```

and `BulletAgeNode`:

```ts
import { Node, keep } from 'ash.ts';
import { Bullet } from '../components';

export class BulletAgeNode extends Node<BulletAgeNode> {
  @keep(Bullet)
  public bullet!:Bullet;
}
```

**Comment by icek** [comment]
I just saw your edit. If you use ash.ts in node environment there might be some issues. In fact it may be the change you have given. Map is a ES6 data structure so check if your node version supports ES6.

**Comment by Maniae** [comment]
I had it working by adding the `@keep` decorator in my node . Didn't notice it was necessary until I read the source code 😅. Thank you for the quick answer.
